### ISSUE TITLE
What's the intended use-case?

### ISSUE THREAD

**Issue by klickreflex** [benface/tailwindcss-alt#2]
This looks like a very useful plugin. The immediate use-case I came up with was something like dark mode toggling, but I'd be curious to know your reasoning behind it was.

**Comment by benface** [comment]
Thanks for your interest @klickreflex! There are different use cases, but dark mode toggling is definitely one. In that sense, it works similarly to [this plugin](https://github.com/ChanceArthur/tailwindcss-dark-mode), but I wanted mine to be more generic because I don't only use it for theming purposes (and back when I made this plugin, the dark mode one didn't have the ability to customize the `.mode-dark` selector).

What I've mainly used it for is components that have two distinct states. For instance recently I've implemented an input autocomplete dropdown with a library, which offers to add a class to the currently highlighted item. A couple different things change visually when an item is highlighted, which would have been a great use case for the `hover` and `group-hover` variants, but it's not just on `hover` or even `focus` that things need to change, because you can also navigate through the items with the up and down keyboard arrow keys. So I set the "highlighted" class to `alt` and thanks to this plugin I can now completely change everything inside the item when it's highlighted, with just CSS instead of JS.

Do you think I should add examples to the README?

**Comment by klickreflex** [comment]
Hi @benface and thanks for explaining, I can totally see the use for it it's a good idea to add some examples to the README 👍

**Comment by benface** [comment]
I added an "Introduction" section to the README in https://github.com/benface/tailwindcss-alt/commit/86d2aafbd3665443c6ac09b10c51e5c914cc3109 which I think explains the different use cases pretty succinctly. Thanks for creating this issue!
